###
// Register User
POST http://localhost:9999/api/users
Content-Type: application/json
Accept: application/json

{
  "role": "petani",
  "nama": "Petani Test",
  "alamat": "Test",
  "nomorTelepon": "123",
  "email": "petani.test@example.com",
  "password": "test"
}

###
// Login User
POST http://localhost:9999/api/users/login
Content-Type: application/json
Accept: application/json

{
  "email": "petani.test@example.com",
  "password": "test"
}

###
// Get Current User
GET http://localhost:9999/api/users/me
Content-Type: application/json
Accept: application/json
