###
// Register User PKS
POST http://localhost:9999/api/users
Content-Type: application/json
Accept: application/json

{
  "role": "pks",
  "nama": "PKS Test",
  "alamat": "Jl PKS Test",
  "nomorTelepon": "081234567890",
  "email": "pks.test@gmail.com",
  "password": "test"
}

###
// Register User Koperasi
POST http://localhost:9999/api/users
Content-Type: application/json
Accept: application/json

{
  "role": "koperasi",
  "nama": "Koperasi Test",
  "alamat": "Jl Koperasi Test",
  "nomorTelepon": "081234567890",
  "email": "koperasi.test@gmail.com",
  "password": "test"
}

###
// Login User PKS
POST http://localhost:9999/api/users/login
Content-Type: application/json
Accept: application/json

{
  "email": "pks.test@gmail.com",
  "password": "test"
}

###
// Login User Koperasi
POST http://localhost:9999/api/users/login
Content-Type: application/json
Accept: application/json

{
  "email": "koperasi.test@gmail.com",
  "password": "test"
}

###
// Get Current User
GET http://localhost:9999/api/users/me
Content-Type: application/json
Accept: application/json

###
// Logout User
DELETE http://localhost:9999/api/users/logout
Content-Type: application/json
Accept: application/json


###
// Inisialisasi Referensi Harga
POST http://localhost:9999/api/referensi-harga-init
Content-Type: application/json
Accept: application/json

###
// Tambah Referensi Harga
POST http://localhost:9999/api/referensi-harga
Content-Type: application/json
Accept: application/json

{
  "umurTanam": 1,
  "harga": 0
}

###
// Ubah Referensi Harga
PUT http://localhost:9999/api/referensi-harga/:idReferensiHarga
Content-Type: application/json
Accept: application/json

{
  "umurTanam": 1,
  "harga": 1000
}

###
// Get All Referensi Harga
GET http://localhost:9999/api/referensi-harga
Content-Type: application/json
Accept: application/json

###
// Get Transaksi with History
GET http://localhost:9999/api/referensi-harga/:idReferensiHarga
Content-Type: application/json
Accept: application/json


###
// Tambah Kebun
POST http://localhost:9999/api/users/petani/kebun
Content-Type: application/json
Accept: application/json

{
  "alamat": "Jl Kebun Test I",
  "latitude": "107.609810",
  "longitude": "-6.914744",
  "luas": 50,
  "nomorRspo": "RSPO-1234567890",
  "sertifikatRspo": "sertifikat-rspo-1234567890.pdf"
}

###
// Ubah Kebun
PUT http://localhost:9999/api/users/petani/kebun/:idKebun
Content-Type: application/json
Accept: application/json

{
  "alamat": "Jl Kebun Test II",
  "latitude": "107.609810",
  "longitude": "-6.914744",
  "luas": 100,
  "nomorRspo": "RSPO-1234567890",
  "sertifikatRspo": "sertifikat-rspo-1234567890.pdf"
}

###
// Get All Kebun by ID Petani
GET http://localhost:9999/api/users/petani/kebun
Content-Type: application/json
Accept: application/json

###
// Get Kebun with History
GET http://localhost:9999/api/users/petani/kebun/:idKebun
Content-Type: application/json
Accept: application/json


###
// Tambah Kontrak by PKS
POST http://localhost:9999/api/rantai-pasok/kontrak
Content-Type: application/json
Accept: application/json

{
  "idKoperasi": "",
  "tanggalMulai": "2023-01-01",
  "tanggalSelesai": "2023-12-31",
  "kuantitas": 12000,
  "harga": 1000
}


###
// Konfirmasi Kontrak by Koperasi
PUT http://localhost:9999/api/rantai-pasok/kontrak/:idKontrak
Content-Type: application/json
Accept: application/json

{
  "idPks": "",
  "status": 1,
  "pesan": "OK. Kami setuju dengan kontrak tersebut."
}
