###
// Register User
POST http://localhost:9999/api/users
Content-Type: application/json
Accept: application/json

{
  "role": "petani",
  "nama": "Petani Test",
  "alamat": "Jl Petani Test",
  "nomorTelepon": "081234567890",
  "email": "petani.test@gmail.com",
  "password": "test"
}

###
// Login User
POST http://localhost:9999/api/users/login
Content-Type: application/json
Accept: application/json

{
  "email": "petani.test@gmail.com",
  "password": "test"
}

###
// Get Current User
GET http://localhost:9999/api/users/me
Content-Type: application/json
Accept: application/json

###
// Logout User
DELETE http://localhost:9999/api/users/logout
Content-Type: application/json
Accept: application/json


###
// Inisialisasi Referensi Harga
POST http://localhost:9999/api/referensi-harga-init
Content-Type: application/json
Accept: application/json

###
// Tambah Referensi Harga
POST http://localhost:9999/api/referensi-harga
Content-Type: application/json
Accept: application/json

{
  "umurTanam": 1,
  "harga": 0
}

###
// Ubah Referensi Harga
PUT http://localhost:9999/api/referensi-harga/:idReferensiHarga
Content-Type: application/json
Accept: application/json

{
  "umurTanam": 1,
  "harga": 1000
}

###
// Get All Referensi Harga
GET http://localhost:9999/api/referensi-harga
Content-Type: application/json
Accept: application/json

###
// Get Transaksi with History
GET http://localhost:9999/api/referensi-harga/:idReferensiHarga
Content-Type: application/json
Accept: application/json


###
// Tambah Kebun
POST http://localhost:9999/api/users/petani/kebun
Content-Type: application/json
Accept: application/json

{
  "alamat": "Jl Kebun Test",
  "latitude": "107.609810",
  "longitude": "-6.914744",
  "luas": 400,
  "nomorRspo": "RSPO-1234567890",
  "sertifikatRspo": "sertifikat-rspo-1234567890.pdf"
}
